-- Tabel untuk pesan terjadwal
CREATE TABLE IF NOT EXISTS public.scheduled_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    phone_number TEXT NOT NULL,
    message TEXT NOT NULL,
    scheduled_at TIMESTAMP WITH TIME ZONE NOT NULL,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'sent', 'failed')),
    repeat_interval TEXT DEFAULT 'none' CHECK (repeat_interval IN ('none', 'daily', 'weekly', 'monthly')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tambahkan kolom repeat_interval jika belum ada (Migration)
DO $$ 
BEGIN
    BEGIN
        ALTER TABLE public.scheduled_messages ADD COLUMN repeat_interval TEXT DEFAULT 'none' CHECK (repeat_interval IN ('none', 'daily', 'weekly', 'monthly'));
    EXCEPTION
        WHEN duplicate_column THEN NULL;
    END;
END $$;

-- Enable RLS
ALTER TABLE public.scheduled_messages ENABLE ROW LEVEL SECURITY;

-- Policies
DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'scheduled_messages' AND policyname = 'Users can view own messages') THEN
    CREATE POLICY "Users can view own messages" ON public.scheduled_messages FOR SELECT USING (auth.uid() = user_id);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'scheduled_messages' AND policyname = 'Users can insert own messages') THEN
    CREATE POLICY "Users can insert own messages" ON public.scheduled_messages FOR INSERT WITH CHECK (auth.uid() = user_id);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'scheduled_messages' AND policyname = 'Users can delete own messages') THEN
    CREATE POLICY "Users can delete own messages" ON public.scheduled_messages FOR DELETE USING (auth.uid() = user_id);
  END IF;
END $$;

-- Function for Bot to fetch pending messages (SECURITY DEFINER to bypass RLS)
-- Updated to include repeat_interval
DROP FUNCTION IF EXISTS get_pending_scheduled_messages();
CREATE OR REPLACE FUNCTION get_pending_scheduled_messages()
RETURNS TABLE (
  id BIGINT,
  phone_number TEXT,
  message TEXT,
  scheduled_at TIMESTAMP WITH TIME ZONE,
  repeat_interval TEXT
) 
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT 
    sm.id,
    sm.phone_number,
    sm.message,
    sm.scheduled_at,
    sm.repeat_interval
  FROM public.scheduled_messages sm
  WHERE 
    sm.status = 'pending' 
    AND sm.scheduled_at <= NOW();
END;
$$ LANGUAGE plpgsql;

-- Function for Bot to mark message as sent AND reschedule if needed
DROP FUNCTION IF EXISTS mark_scheduled_message_sent(BIGINT, TEXT);
CREATE OR REPLACE FUNCTION mark_scheduled_message_sent(msg_id BIGINT, new_status TEXT, next_schedule TIMESTAMP WITH TIME ZONE DEFAULT NULL)
RETURNS VOID
SECURITY DEFINER
AS $$
BEGIN
  IF next_schedule IS NOT NULL THEN
    -- Jika ada repeat, reset status ke 'pending' dan update waktu jadwal
    UPDATE public.scheduled_messages
    SET status = 'pending', scheduled_at = next_schedule, updated_at = NOW()
    WHERE id = msg_id;
  ELSE
    -- Jika tidak repeat, mark as sent/failed
    UPDATE public.scheduled_messages
    SET status = new_status, updated_at = NOW()
    WHERE id = msg_id;
  END IF;
END;
$$ LANGUAGE plpgsql;
